### ISSUE TITLE
LLVM Build Discussion (Archived)

### ISSUE THREAD

**Issue by RobRich999** [RobRich999/LLVM_Optimized_AVX2#1]
FYI. I am providing an AVX2 optimized LLVM checkout for Linux. I will try to keep it upgraded on a maybe weekly or bi-weekly release cycle.

https://github.com/RobRich999/LLVM_Optimized_AVX2

The binary release includes basically the same files as the default LLVM checkout included with Chromium, though only with x86-64 support at this time. I have verified the release package works to build Chromium for Linux, and barring no issues, it should suffice for Windows cross builds as well.

LLVM optimizations include -march=x86-64-v3, -O3, Polly, LTO, PGO, BOLT, and the mimalloc allocator. FWIW, note the libxml2 library and mimalloc allocator are currently built with GCC and several of its optimizations.

**Comment by RobRich999** [comment]
An updated LLVM release is available. Updated diff as well.

In particular BOLT was not being trained against the cflags/cxxflags I wanted due to appending the wrong cmake arguments. It should be fixed now.

Also rolled my latest Linux and Windows cross builds with the current release package. Worked fined, at least for me.

**Comment by RobRich999** [comment]
Disabled GOMA in the build script. I suspect none of us here have access anyway.

Added -enable-ext-tsp-block-placement when using PGO. Chromium devs have noted a small performance uplift with the pass. Might as well try it with LLVM.

I need to do something about mimalloc. Probably just a build conditional initially. Actually adding it to the script to download and build probably is doable, if/when I maybe feel like poking at the needed code.

**Comment by RobRich999** [comment]
I forget to get a diff for the r08be779 release. I will try to update the patch in the near future.

**Comment by RobRich999** [comment]
The compiler-rt libraries for Windows are missing in the r08be779 release, so no cross building for now. I will need to roll an updated release once resolved.

**Comment by RobRich999** [comment]
Currently I am working on cleaning up my script mods and removing some of my previously added platform/tools conditionals. Hope to have a diff patch and release build pushed soon.

**Comment by RobRich999** [comment]
I change the opt levels to -O2 for experimentation. I doubt there will be much performance difference, but a quick FYI anyway.

**Comment by RobRich999** [comment]
Just noticed the compiler-rt libraries for Windows are still missing. Modifying the build script to explicitly include Windows support when building compiler-rt and trying again.

----------------

It did not like that, either. Hmmm.

----------------

I suspect a standalone Windows build of compiler-rt would be a better place to start. Maybe later. For now I am simply copying the compiler-rt libraries for Windows from Chromium's bundled LLVM package. It is not ideal, but it should be okay as long as revisions are not too far apart.

**Comment by RobRich999** [comment]
Seems I am not alone:

Issue 1462401: linux-win_cross-rel: missing clang_rt.builtins-x86_64.lib
https://bugs.chromium.org/p/chromium/issues/detail?id=1462401

**Comment by enginelesscc** [comment]
I'd love to see windows releases once all of that is sorted out

**Comment by RobRich999** [comment]
Not sure Windows native releases of my LLVM builds will happen anytime soon, as I have little use for the platform these days. That said, I will not entirely dismiss the idea. First I would have to setup a Windows virtualized environment on my Xeon 96c/192t build server, as my current Windows native Opteron 32c build server does not support AVX2.

**Comment by gz83** [comment]
Hello Rob, I applied the llvm patch and commands you provided and tried to compile llvm, but I encountered the following errors during the compilation process. I have confirmed that the libxml2 and libxml2-dev packages have been installed. I am using Ubuntu 22.04 system.

Could you please take a look for me?

@RobRich999 

Building instrumented compiler
Running cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=OFF '-DLLVM_ENABLE_PROJECTS=clang;lld;clang-tools-extra;polly;bolt' -DLLVM_ENABLE_RUNTIMES=compiler-rt '-DLLVM_TARGETS_TO_BUILD=AArch64;ARM;LoongArch;Mips;PowerPC;RISCV;SystemZ;WebAssembly;X86' -DLLVM_ENABLE_PIC=ON -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_ENABLE_Z3_SOLVER=OFF -DCLANG_PLUGIN_SUPPORT=OFF -DCLANG_ENABLE_STATIC_ANALYZER=OFF -DCLANG_ENABLE_ARCMT=OFF '-DBUG_REPORT_URL=https://crbug.com in the Tools>LLVM component, run tools/clang/scripts/process_crashreports.py (only if inside Google) to upload crash related files,' -DLLVM_ENABLE_DIA_SDK=OFF -DLLVM_ENABLE_LLD=ON -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF -DLLVM_ENABLE_CURL=OFF -DLIBCLANG_BUILD_STATIC=ON -DLLVM_ENABLE_UNWIND_TABLES=OFF -DLLVM_STATIC_LINK_CXX_STDLIB=ON -DCMAKE_SYSROOT=/home/ho/chromium/src/third_party/llvm-build-tools/debian_bullseye_amd64_sysroot -DLLVM_ENABLE_LIBXML2=FORCE_ON -DLIBXML2_INCLUDE_DIR=/home/ho/chromium/src/third_party/llvm-build-tools/libxml2-v2.9.12/build/install/include/libxml2 -DLIBXML2_LIBRARIES=/home/ho/chromium/src/third_party/llvm-build-tools/libxml2-v2.9.12/build/install/lib/libxml2.a -DLIBXML2_LIBRARY=/home/ho/chromium/src/third_party/llvm-build-tools/libxml2-v2.9.12/build/install/lib/libxml2.a -DCLANG_ENABLE_LIBXML2=NO -DLLVM_ENABLE_ZSTD=ON -DLLVM_USE_STATIC_ZSTD=ON -Dzstd_INCLUDE_DIR=/home/ho/chromium/src/third_party/llvm-build-tools/zstd-1.5.5/cmake_build/install/include -Dzstd_LIBRARY=/home/ho/chromium/src/third_party/llvm-build-tools/zstd-1.5.5/cmake_build/install/lib/libzstd.a '-DLLVM_ENABLE_PROJECTS=clang;polly' '-DCMAKE_C_FLAGS=-mllvm -vp-counters-per-site=3 -mllvm -polly -mllvm -polly-invariant-load-hoisting -O3 -DNDEBUG -w -march=x86-64-v3 -ffp-contract=fast -fmerge-all-constants -fdata-sections -ffunction-sections -DSANITIZER_OVERRIDE_INTERCEPTORS -I/home/ho/chromium/src/tools/clang/scripts/sanitizers -DLIBXML_STATIC' '-DCMAKE_CXX_FLAGS=-mllvm -vp-counters-per-site=3 -mllvm -polly -mllvm -polly-invariant-load-hoisting -O3 -DNDEBUG -w -march=x86-64-v3 -ffp-contract=fast -fmerge-all-constants -fdata-sections -ffunction-sections -DSANITIZER_OVERRIDE_INTERCEPTORS -I/home/ho/chromium/src/tools/clang/scripts/sanitizers -DLIBXML_STATIC' '-DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld -Wl,-O2 -Wl,--gc-sections -Wl,--icf=all -Wl,--as-needed -Wl,--push-state,/home/ho/work/mimalloc/out/release/libmimalloc.a,--pop-state' '-DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=lld -Wl,-O2 -Wl,--gc-sections -Wl,--icf=all -Wl,--as-needed -Wl,--push-state,/home/ho/work/mimalloc/out/release/libmimalloc.a,--pop-state' '-DCMAKE_MODULE_LINKER_FLAGS=-fuse-ld=lld -Wl,-O2 -Wl,--gc-sections -Wl,--icf=all -Wl,--as-needed -Wl,--push-state,/home/ho/work/mimalloc/out/release/libmimalloc.a,--pop-state' -DLLVM_BUILD_INSTRUMENTED=IR -DCMAKE_C_COMPILER=/home/ho/chromium/src/third_party/llvm-bootstrap-install/bin/clang -DCMAKE_CXX_COMPILER=/home/ho/chromium/src/third_party/llvm-bootstrap-install/bin/clang++ /home/ho/chromium/src/third_party/llvm/llvm
-- The C compiler identification is Clang 18.0.0
-- The CXX compiler identification is Clang 18.0.0
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /home/ho/chromium/src/third_party/llvm-bootstrap-install/bin/clang
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/ho/chromium/src/third_party/llvm-bootstrap-install/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/ho/chromium/src/third_party/llvm-bootstrap-install/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- bolt project is disabled
-- clang project is enabled
-- clang-tools-extra project is disabled
-- compiler-rt project is disabled
-- cross-project-tests project is disabled
-- libc project is disabled
-- libclc project is disabled
-- lld project is disabled
-- lldb project is disabled
-- mlir project is disabled
-- openmp project is disabled
-- polly project is enabled
-- pstl project is disabled
-- flang project is disabled
-- Found Python3: /home/ho/.vpython-root/3c2f4d/bin/python3.8 (found suitable version "3.8.10", minimum required is "3.6") found components: Interpreter 
-- Performing Test LLVM_LIBSTDCXX_MIN
-- Performing Test LLVM_LIBSTDCXX_MIN - Success
-- Performing Test LLVM_LIBSTDCXX_SOFT_ERROR
-- Performing Test LLVM_LIBSTDCXX_SOFT_ERROR - Success
-- Performing Test CXX_COMPILER_SUPPORTS_STATIC_STDLIB
-- Performing Test CXX_COMPILER_SUPPORTS_STATIC_STDLIB - Success
-- Performing Test CXX_LINKER_SUPPORTS_STATIC_STDLIB
-- Performing Test CXX_LINKER_SUPPORTS_STATIC_STDLIB - Success
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for errno.h
-- Looking for errno.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for link.h
-- Looking for link.h - found
-- Looking for malloc/malloc.h
-- Looking for malloc/malloc.h - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for signal.h
-- Looking for signal.h - found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for sys/param.h
-- Looking for sys/param.h - found
-- Looking for sys/resource.h
-- Looking for sys/resource.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for sysexits.h
-- Looking for sysexits.h - found
-- Looking for termios.h
-- Looking for termios.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for valgrind/valgrind.h
-- Looking for valgrind/valgrind.h - found
-- Looking for fenv.h
-- Looking for fenv.h - found
-- Looking for FE_ALL_EXCEPT
-- Looking for FE_ALL_EXCEPT - found
-- Looking for FE_INEXACT
-- Looking for FE_INEXACT - found
-- Performing Test HAVE_BUILTIN_THREAD_POINTER
-- Performing Test HAVE_BUILTIN_THREAD_POINTER - Success
-- Looking for mach/mach.h
-- Looking for mach/mach.h - not found
-- Looking for CrashReporterClient.h
-- Looking for CrashReporterClient.h - not found
-- Looking for linux/magic.h
-- Looking for linux/magic.h - found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Looking for pthread_rwlock_init in pthread
-- Looking for pthread_rwlock_init in pthread - found
-- Looking for pthread_mutex_lock in pthread
-- Looking for pthread_mutex_lock in pthread - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for pfm_initialize in pfm
-- Looking for pfm_initialize in pfm - not found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found ZLIB: /home/ho/chromium/src/third_party/llvm-build-tools/debian_bullseye_amd64_sysroot/usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")  
-- Looking for compress2
-- Looking for compress2 - found
-- Found LibXml2: /home/ho/chromium/src/third_party/llvm-build-tools/libxml2-v2.9.12/build/install/lib/libxml2.a (found version "2.9.10") 
-- Looking for xmlReadMemory
-- Looking for xmlReadMemory - not found
CMake Error at cmake/config-ix.cmake:176 (message):
  Failed to configure libxml2
Call Stack (most recent call first):
  CMakeLists.txt:872 (include)


-- Configuring incomplete, errors occurred!
Failed.

**Comment by RobRich999** [comment]
@gz83 It pulls in libxml2 from an earlier build step instead of the system library. Sounds like it is not being built properly. Did you remove the instances of...

-Wl,--push-state,/home/robrich/Downloads/mimalloc/build/libmimalloc.a,--pop-state

....from the build script? Alternatively, you can locally build mimalloc and point the above invocation at your local copy.

**Comment by gz83** [comment]
> @gz83 It pulls in libxml2 from an earlier build step instead of the system library. Sounds like it is not being built properly. Did you remove the instances of...
> 
> -Wl,--push-state,/home/robrich/Downloads/mimalloc/build/libmimalloc.a,--pop-state
> 
> ....from the build script? Alternatively, you can locally build mimalloc and point the above invocation at your local copy.

Before I used the patch you provided to patch the build.py file, I had already compiled mimalloc locally, and installed it into the system with the make install command, and also modified the path of mimalloc in the build.py file synchronously.

I tried to compile with mimalloc and without mimalloc, and got the following results:

Introducing mimalloc: getting the error above
Not introducing mimalloc: getting linker errors that are quite different from the one above

At the same time, I also tried to compile using the original build.py file, and everything worked fine, I still don't know how to solve the error mentioned earlier.

@RobRich999

**Comment by RobRich999** [comment]
@gz83 Just tried on my Kubuntu 23.04 notebook....

```
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.13")  
-- Looking for compress2
-- Looking for compress2 - found
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.14") 
-- Looking for xmlReadMemory
-- Looking for xmlReadMemory - found
```

Curious, how are you building mimalloc? Mine using GCC 13.1...

`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_ASM_FLAGS_RELEASE="-O3 -DNDEBUG -w -march=x86-64-v3 -fgraphite -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=auto -fdevirtualize-at-ltrans -fdata-sections -ffunction-sections -pipe" -DCMAKE_C_FLAGS_RELEASE="-O3 -DNDEBUG -w -march=x86-64-v3 -fgraphite -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=auto -fdevirtualize-at-ltrans -fdata-sections -ffunction-sections -pipe" -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -w -march=x86-64-v3 -fgraphite -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=auto -fdevirtualize-at-ltrans -fdata-sections -ffunction-sections -pipe" -DCMAKE_EXE_LINKER_FLAGS="-O3 -DNDEBUG -w -march=x86-64-v3 -fgraphite -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=auto -fdevirtualize-at-ltrans -fdata-sections -ffunction-sections -pipe -Wl,-O1 -Wl,--gc-sections" -DCMAKE_SHARED_LINKER_FLAGS="-O3 -DNDEBUG -w -march=x86-64-v3 -fgraphite -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=auto -fdevirtualize-at-ltrans -fdata-sections -ffunction-sections -pipe -Wl,-O1 -Wl,--gc-sections" -DCMAKE_MODULE_LINKER_FLAGS="-O3 -DNDEBUG -w -march=x86-64-v3 -fgraphite -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=auto -fdevirtualize-at-ltrans -fdata-sections -ffunction-sections -pipe -Wl,-O1 -Wl,--gc-sections" ..`

**Comment by gz83** [comment]
> @gz83 Just tried on my Kubuntu 23.04 notebook....
> 
> ```
> -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.13")  
> -- Looking for compress2
> -- Looking for compress2 - found
> -- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.14") 
> -- Looking for xmlReadMemory
> -- Looking for xmlReadMemory - found
> ```
> 
> Curious, how are you building mimalloc? Mine using GCC 13.1...
> 
> `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_ASM_FLAGS_RELEASE="-O3 -DNDEBUG -w -march=x86-64-v3 -fgraphite -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=auto -fdevirtualize-at-ltrans -fdata-sections -ffunction-sections -pipe" -DCMAKE_C_FLAGS_RELEASE="-O3 -DNDEBUG -w -march=x86-64-v3 -fgraphite -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=auto -fdevirtualize-at-ltrans -fdata-sections -ffunction-sections -pipe" -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -w -march=x86-64-v3 -fgraphite -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=auto -fdevirtualize-at-ltrans -fdata-sections -ffunction-sections -pipe" -DCMAKE_EXE_LINKER_FLAGS="-O3 -DNDEBUG -w -march=x86-64-v3 -fgraphite -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=auto -fdevirtualize-at-ltrans -fdata-sections -ffunction-sections -pipe -Wl,-O1 -Wl,--gc-sections" -DCMAKE_SHARED_LINKER_FLAGS="-O3 -DNDEBUG -w -march=x86-64-v3 -fgraphite -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=auto -fdevirtualize-at-ltrans -fdata-sections -ffunction-sections -pipe -Wl,-O1 -Wl,--gc-sections" -DCMAKE_MODULE_LINKER_FLAGS="-O3 -DNDEBUG -w -march=x86-64-v3 -fgraphite -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=auto -fdevirtualize-at-ltrans -fdata-sections -ffunction-sections -pipe -Wl,-O1 -Wl,--gc-sections" ..`

I followed the instructions given in the mimalloc repo to compile

https://github.com/microsoft/mimalloc?tab=readme-ov-file#macos-linux-bsd-etc

`
> mkdir -p out/release
> cd out/release
> cmake ../..
> make

`

The GCC toolchain should be undamaged, using the version corresponding to Ubuntu 22.04

@RobRich999

**Comment by RobRich999** [comment]
@gz83 I suspect you have a linker issue somewhere in the mix, but first up, try commenting out the cflags and ldflags under the BuildLibXml2 section.

```
#  '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG -w -march=x86-64-v3 -ffp-contract=fast -fipa-pta -fgraphite-identity -floop-nest-optimize -pipe -fdata-sections -ffunction-sections ',
# '-DCMAKE_EXE_LINKER_FLAGS=-Wl,-O1 -Wl,--gc-sections -Wl,--as-needed -Wl,--push-state,/mnt/raid0/source_builds/mimalloc/build/libmimalloc.a,--pop-state ',
# '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-O1 -Wl,--gc-sections -Wl,--as-needed -Wl,--push-state,/mnt/raid0/source_builds/mimalloc/build/libmimalloc.a,--pop-state ',
# '-DCMAKE_MODULE_LINKER_FLAGS=-Wl,-O1 -Wl,--gc-sections -Wl,--as-needed -Wl,--push-state,/mnt/raid0/source_builds/mimalloc/build/libmimalloc.a,--pop-state ',
```

If that resolves it, you can try trimming down the options. For example, forget the link flags and just set a basic cflag string....

`'-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG -w -march=x86-64-v3',`

....or march=haswell, native, or whatever works for your purposes.

Also you can try setting -DLLVM_ENABLE_LIBXML2=OFF in the LLVM cmake args in the script if absolutely required, but it will probably break any Clang tests that call into llvm-mt. YMMV. That said, it seems to be working for you with the default script, so I suggest first looking at how BuildLibXml2 is being built as noted above.

**Comment by RobRich999** [comment]
I have added a build script optimization change to set -march=x86-64-v3 -mprefer-vector-width=128 (and the equivalent gcc opt) for testing. That might benefit older procs affecting by AVX2 frequency scaling, while I suspect LLVM performance differences with modern AVX2 procs will be largely trivial; or perhaps even in the noise.

Even preferring 128-bit AVX/AVX2, LLVM for the x86-64-v3 arch target will still generate certain 256-bit "light" instructions like load/store that do not typically affect AVX2 frequency scaling. ;)

https://github.com/llvm/llvm-project/commit/d7043e8c41bb74a31c9790616c1536596814567b
https://en.wikichip.org/wiki/intel/frequency_behavior

Not sure what GCC does with -mprefer-avx128 regarding possible generation of any 256-bit "light" AVX2 instructions, but only xml2, zstd, and mimalloc (in my release builds) are built with GCC anyway, so no big deal IMHO.

----

I will probably look into transitioning mimalloc to LLVM as well.

----

Dropping mimalloc for awhile while I try sorting out some issues.

Dropping Polly optimization of the LLVM build as well for testing. I suspect little to no performance difference. Note Polly as a component of LLVM is still being built.

Simplified various optimizations in the script. I will reevaluate those optimizations over the next build iteration or few.

**Comment by RobRich999** [comment]
Various optimizations restored in build f061b13. AVX2 as usual, but with the previously mentioned -mprefer-vector-width=128 option set. Mimalloc restored as well, though still built with GCC.

BTW, using the ThinLTO option on my 96c/192t build box incurred rather extended build times with the current LLVM patch, but it did eventually complete. Patience recommended, and YMMV as usual.

**Comment by gz83** [comment]
> @gz83 I suspect you have a linker issue somewhere in the mix, but first up, try commenting out the cflags and ldflags under the BuildLibXml2 section.
> 
> ```
> #  '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG -w -march=x86-64-v3 -ffp-contract=fast -fipa-pta -fgraphite-identity -floop-nest-optimize -pipe -fdata-sections -ffunction-sections ',
> # '-DCMAKE_EXE_LINKER_FLAGS=-Wl,-O1 -Wl,--gc-sections -Wl,--as-needed -Wl,--push-state,/mnt/raid0/source_builds/mimalloc/build/libmimalloc.a,--pop-state ',
> # '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-O1 -Wl,--gc-sections -Wl,--as-needed -Wl,--push-state,/mnt/raid0/source_builds/mimalloc/build/libmimalloc.a,--pop-state ',
> # '-DCMAKE_MODULE_LINKER_FLAGS=-Wl,-O1 -Wl,--gc-sections -Wl,--as-needed -Wl,--push-state,/mnt/raid0/source_builds/mimalloc/build/libmimalloc.a,--pop-state ',
> ```
> 
> If that resolves it, you can try trimming down the options. For example, forget the link flags and just set a basic cflag string....
> 
> `'-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG -w -march=x86-64-v3',`
> 
> ....or march=haswell, native, or whatever works for your purposes.
> 
> Also you can try setting -DLLVM_ENABLE_LIBXML2=OFF in the LLVM cmake args in the script if absolutely required, but it will probably break any Clang tests that call into llvm-mt. YMMV. That said, it seems to be working for you with the default script, so I suggest first looking at how BuildLibXml2 is being built as noted above.

@RobRich999 

Hi robrich, sorry for taking so long to reply to you. I reinstalled the system and deployed the relevant environment, and commented out libmimallc. Now I have successfully compiled llvm. I will try to use it in the process of compiling Chromium later.

The compilation command I use is provided in your repo. How should I extract the compiled finished product for subsequent use? (like the llvm you posted in this repo)

**Comment by RobRich999** [comment]
@gz83 Extract my release build compressed archive wherever, then add the path and version to your args.gn config when building. For example:

clang_base_path = "/mnt/raid0/llvm"
clang_version = "18"

Another example if interested in using a [LLVM project build:](https://apt.llvm.org/)

clang_base_path = "/usr/lib/llvm-18"
clang_version = "18"

If using the Chromium build script on your local system, the resulting build replaces the packaged LLVM build in third_party/llvm-build. You do not have to do anything to the args.gn config for it to work.

Note that doing a gclient sync will overwrite the files to restore the packaged LLVM build. If wanting to save your build build, you can move the contents of the Release_Asserts directory, then use the path and revision strings in the args.gn config as noted above.

I packaged my release builds manually. You can look at my LLVM release build directories and files to determine what is needed for building Chromium if perhaps interested in doing a LLVM public release build.

Admittedly, I copy the Windows library files for compiler-rt from the packaged builds into my release builds, as it is simpler than trying to build Windows compiler-rt on Linux. ;)

third_party/llvm-build/Release+Asserts/lib/clang/18/lib/windows/

Same for the libstdc++.so.6 library if present, though it is likely unneeded in most cases, plus the llvm-symbolizer.exe binary for whatever reason the Chromium devs bundle it on Linux.

Once you have all the needed files, you can compress them with whatever utility. I use zx. For example, to compress the llvm release directory:

tar -cf - llvm | xz -9 -e --threads=0 --memory=90% > llvm-v18-rf061b13-linux64-avx2.tar.x

The truncated revision number is derived from running clang -v.

You might want to adjust or change those zx parameters according to your system hardware. My build server has 256GB of memory, so it is unlikely xz will ever hit 90% memory usage compressing my LLVM release.

**Comment by gz83** [comment]
> @gz83 Extract my release build compressed archive wherever, then add the path and version to your args.gn config when building. For example:
> 
> clang_base_path = "/mnt/raid0/llvm" clang_version = "18"
> 
> Another example if interested in using a [LLVM project build:](https://apt.llvm.org/)
> 
> clang_base_path = "/usr/lib/llvm-18" clang_version = "18"
> 
> If using the Chromium build script on your local system, the resulting build replaces the packaged LLVM build in third_party/llvm-build. You do not have to do anything to the args.gn config for it to work.
> 
> Note that doing a gclient sync will overwrite the files to restore the packaged LLVM build. If wanting to save your build build, you can move the contents of the Release_Asserts directory, then use the path and revision strings in the args.gn config as noted above.
> 
> You can look at my LLVM release build directories and files to determine what is needed for building Chromium if perhaps interested in doing a LLVM public release build. Admittedly, I copy the Windows library files for compiler-rt from the packaged builds into my release builds, as it is simpler than trying to build Windows compiler-rt on Linux. ;)
> 
> third_party/llvm-build/Release+Asserts/lib/clang/18/lib/windows/
> 
> Same for the llvm-symbolizer.exe binary for whatever reason the Chromium devs bundle it on Linux, too. I do not build Chromium debug symbols, so "whatever" I suppose.

Thanks for your reply, I understand

@RobRich999

**Comment by RobRich999** [comment]
@@gz83 Updated my previous comment with a few more details. Thing you probably already know, but anyway, if anyone else if following along with the discussion.

**Comment by RobRich999** [comment]
Hopefully I should have an updated LLVM AVX2 diff and build later today.

I finally got around to pulling mimalloc into the build script, too. It downloads and builds early in the process. I am waiting on a completed LLVM build at the moment, but thus far mimalloc seems to be propagating to the various build steps.

**Comment by RobRich999** [comment]
Updated diff and release build. Mimalloc is now downloaded, compiled, and propagated by the build script.

**Comment by RobRich999** [comment]
Looks like mimalloc might not be overriding malloc. I set the mimalloc environment variable for large pages, and there was no change in the system's free huge pages when running clang, lld, etc. Grrr.

I  tried a LD_PRELOAD environment variable for mimalloc to override malooc, and it started using large pages. Same for other mimalloc environment variables.

It could be because I am not using --whole-archive during linking. Anyway, instead I suppose that I will try setting it as a static override during linking in a future build.

**Comment by RobRich999** [comment]
I have mimalloc working for an internal LLVM build. Hopefully I should have a new build script patch and binaries ready later this week.

----------------

Updated. Rolled an updated internal LLVM build. SLP vectorization during ThinLTO is working as expected, so no patch needed. Anyway.

**Comment by RobRich999** [comment]
Diff patch and LLVM build updated.

Mimalloc is included. It is downloaded, built, and pulled into linker invokes.

I dropped -mprefer-vector-width=128 (for now?). I am not seeing much, if any noticeable difference on my 96c/192t Broadwell build server. We are probably not getting many AVX2 "heavy" instructions when building LLVM. Those with later AVX2 procs might even show a slight improvement. YMMV.

I swapped out the time spent using Polly to build the LLVM binaries in exchange for increasing the LTO import limits, which likely will be more beneficial for most. Note, Polly is still included, and the PGO and Bolt profiles are still trained with it for those using Polly to optimize Chromium or whatever builds.

I moved -Wl,-z,keep-text-section-prefix further up in the build chain. Previously it was only set if BOLT was enabled. I probably could move it down to the final LLVM build, but I suppose whatever anyway.

At some point I might look further into adding back -fsplit-machine-functions, perhaps along with-unique-basic-block-section-names, -bbsections-cold-text-prefix, etc.

----------------

Hit a floating point exception. Hmmm. I will try to revisit in a day or few.

**Comment by RobRich999** [comment]
I might have to roll an updated LLVM build later today or tomorrow.

I hit a significant Speedometer performance regression in Chromium with my usual -O3 across the board config. o.0

Instead building Chromium at split O levels - mostly at O2 - resolved much of it.

I suspect the issue could be on the LLVM side, but I am still investigating it.

**Comment by RobRich999** [comment]
In the meantime I rolled the v120.0.6096.0-r1216665 builds with Chromium's own bundled LLVM checkout.

**Comment by RobRich999** [comment]
Binaries and diff patch updated.

**Comment by RobRich999** [comment]
Using the mimalloc THP environment option **_might_** improve performance of LLVM for the build script and resulting binaries. YMMV.

export MIMALLOC_ALLOW_LARGE_OS_PAGES=1

More info at the mimalloc project page.

https://github.com/microsoft/mimalloc#environment-options

**Comment by RobRich999** [comment]
Been poking at some LLVM build script changes. Just rolled an updated internal build to test.

I am disabling mimalloc for now. I might be hitting a regression, and upon skimming the source repo , I am not sure how actively it being developed or supported anymore. Anyway, glibc malloc is working okay enough for our purposes IMO.

I am not digging to far into it, but the default build script is generating a BOLT-optimized clang binary, but not BOLT-optimized clang++ and clang-cl binaries. Since Chromium packages those as symlinks to clang in its own LLVM  checkout, I suspect it is being done in a script elsewhere; perhaps even on the server side there. I still need to test the changes, but adding some copy commands preserving timestamps to the build script should resolve it for our purposes. Compression should handle much of the duplication overhead in the archive package.

Right now BOLT (if used) targets the clang binary and its direct siblings (as noted above). That still leaves lots of other LLVM binaries, so I have pulled in the Machine Function Splitter. It uses the basic blocks feature from Propeller in conjunction with standard PGO data to split functions into hot and cold blocks. Combined with the ext-tsp basic block layout pass I pulled into the script awhile back, we are getting at least a portion of benefits somewhat similar to BOLT or Propeller without having to run even more post-link instrumentation and optimization passes on those additional LLVM binaries.

I updated ThinLTO to enable split LTO units so we can enable -fwhole-program-vtables for whole program devirtualization of vtables. It tends to somewhat slow build times, but it is manageable on my build server.

FWIW, which is probably not much, I changed building of libxml2 and zstd from GCC to the pinned Clang/LLVM download used for creating the LLVM bootstrap build stage in the script.

I stripped out ARM support; yet again. I do not need it for Chromium on x86(-64), and it was causing an annoying build error in a runtime for me. If one wants to cross-build for ARM or whatever other non-x86 platforms Chromium supports, instead use Chromium's own bundled LLVM checkout IMO.

I need to again verify the various changes in the upcoming day or few, then hopefully push diff and build updates.

**Comment by RobRich999** [comment]
Updated diff and build.

At some point I probably should get around to cleaning up and condensing all the various appends and flags I add, but anyway, they work so "whatever" for now IMO.

**Comment by RobRich999** [comment]
Looks like clang-cl is not too happy in my build from yesterday. Hmmm. Could be related to BOLT. Oh well, just use the bundled LLVM checking for cross-building Windows in the meantime.

**Comment by RobRich999** [comment]
Updated diff and build incoming.

Mimalloc is back and being built with Clang.

BOLT and Machine Function Splitting do not play well together. I dropped MFS for now.

The clang++ and clang-cl binaries are now relative symlinks to the clang binary.

I have not tested clang-cl, yet, though hopefully it should work okay now.

**Comment by enginelesscc** [comment]
Managed to build on windows, just took a few changes (clang -> clang-cl & lld-link vs lld param diffs) and had to remove the chrome-trainingdata as that is linux only.

My 7950X luckily went through the build very fast, but.. i only have 32gb ram so the final build sent me into 85GB ram usage during linkage and my pagefile is obviously slower than ram :)
